#!/usr/bin/env bash
# shellcheck disable=SC2034 # RED is part of the shared wizard palette, unused here.
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=3

# The platform's deploy (scripts/deploy-wizard.sh) left its values in the repo
# root .env (gitignored); this wizard reads them from there.
ENV_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/.env"

banner "Onboard a managed project onto the platform"

# ── Stage 1: which repo ───────────────────────────────────────────────────
stage "Pick the managed project's repository"
say "A managed project is an app in its own GitHub repository, deployed by its"
say "own GitHub Actions with Alchemy (ADR-0001). See docs/managed-projects.md"
say "for what its workflows need to do."
note "Run scripts/deploy-wizard.sh first: this wizard reuses the service token"
note "and dashboard URL it saved."
ask PROJECT_REPO "The project's GitHub slug (owner/repo):"
while true; do
  if [[ "$PROJECT_REPO" != */* || -z "${PROJECT_REPO#*/}" || -z "${PROJECT_REPO%%/*}" ]]; then
    warn "'$PROJECT_REPO' isn't \"owner/repo\" — needs exactly one slash, both sides non-empty."
  elif command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1 \
    && ! gh repo view "$PROJECT_REPO" >/dev/null 2>&1; then
    warn "GitHub repo '$PROJECT_REPO' wasn't found (or isn't reachable with the current 'gh' auth)."
    note "The later stages push secrets onto it, so it must exist first."
  else
    break
  fi
  ask PROJECT_REPO "The project's GitHub slug (owner/repo):"
done
write_env PROJECT_REPO "$PROJECT_REPO"

# ── Stage 2: the project's own credentials (ADR-0010) ─────────────────────
# There is no registration route on the control plane (deliberately: it has
# zero token-issuance surface, see ADR-0010). The project's own bootstrap
# stack mints its Cloudflare CI token and its control-plane bearer token,
# writes the bearer token's hash straight into the platform's D1, and pushes
# CLOUDFLARE_API_TOKEN / CLOUDFLARE_ACCOUNT_ID / PROJECT_OPS_TOKEN into the
# project's GitHub secrets itself.
stage "Run the project's credential bootstrap stack"
say "The project mints its own narrowly scoped Cloudflare token and its"
say "control-plane bearer token, and pushes both straight into its GitHub"
say "secrets — nothing to paste back here (ADR-0010)."
say ""
say "It runs under a separate Alchemy profile, 'admin', set up once per machine:"
warn "Minting the CI token needs a Cloudflare profile with a stored API token:"
warn "Cloudflare's token-creation endpoint refuses OAuth sessions (what the"
warn "deploy wizard's default profile is), and no scope fixes that."
step "Cloudflare dashboard -> My Profile -> API Tokens -> Create Token ->"
step "Custom Token, scoped to just 'API Tokens: Edit' (nothing else)."
note "  pnpm alchemy profile edit --profile admin --add Cloudflare"
note "  (choose 'Stored', not OAuth — paste the token from the step above)"
step "Connect GitHub to the same profile; with 'gh' logged in it's no new login:"
note "  pnpm alchemy profile edit --profile admin --add GitHub"
note "  (choose the recommended 'gh CLI' method)"
step "The bearer token's hash is written with 'wrangler d1 execute', which has"
step "its own login: 'wrangler whoami' should show this account."
say ""
CLOUDFLARE_ACCOUNT_ID=$(_existing CLOUDFLARE_ACCOUNT_ID || true)
# The platform's own URL is https://<worker>.<subdomain>.workers.dev.
WORKERS_SUBDOMAIN=$(_existing DASHBOARD_URL | sed -nE 's#^https://[^.]+\.([^.]+)\.workers\.dev.*#\1#p' || true)
pause "Enter once the admin profile and wrangler are set up (or already were)."
_clear
printf "\n%s%s▸ Stage 2/%s · Run the bootstrap, in the project's folder%s\n" \
  "$BOLD" "$BLUE" "$TOTAL_STAGES" "$RESET"
say ""
say "${BOLD}1. Create a file named .env in the project's folder with these lines:${RESET}"
note "  (it's gitignored; none of these values are secrets)"
say ""
say "   CLOUDFLARE_ACCOUNT_ID=${CLOUDFLARE_ACCOUNT_ID:-<account id>}"
say "   GITHUB_REPO=$PROJECT_REPO"
say "   CONTROL_PLANE_DB=production-project-ops-db"
say "   CLOUDFLARE_WORKERS_SUBDOMAIN=${WORKERS_SUBDOMAIN:-<dashboard: Workers & Pages -> Subdomain>}"
say "   CF_ACCESS_TEAM_DOMAIN=$(_existing CF_ACCESS_TEAM_DOMAIN || echo '<team>')"
say "   CF_GOOGLE_IDP_ID=$(_existing CF_GOOGLE_IDP_ID || echo '<google idp id>')"
say "   CF_ACCESS_ALLOW_EMAIL=$(_existing CF_ACCESS_ALLOW_EMAIL || echo '<who may log in>')"
say ""
note "  The last three lock the project's previews and staging behind this"
note "  platform's Google login (same Zero Trust org). A Svelteflare project needs them."
say ""
say "${BOLD}2. Check wrangler is logged in to this account:${RESET}"
say "   pnpm exec wrangler whoami"
say ""
say "${BOLD}3. Run the bootstrap, and approve its plan:${RESET}"
say "   ALCHEMY_PROFILE=admin pnpm bootstrap:github"
note "  It ends with: Verified CI token refreshed in Cloudflare, GitHub, and Alchemy state."
say ""
# Don't move on until the bootstrap's secrets are on the repo: everything
# after this, and every deploy, depends on them.
while true; do
  pause "Enter when the bootstrap has finished."
  if ! command -v gh >/dev/null 2>&1 || ! gh auth status >/dev/null 2>&1; then
    warn "gh isn't logged in, so I can't check the repo's secrets. Carrying on."
    break
  fi
  existing_secrets=$(gh secret list --repo "$PROJECT_REPO" 2>/dev/null | cut -f1)
  missing=()
  for name in CLOUDFLARE_API_TOKEN CLOUDFLARE_ACCOUNT_ID PROJECT_OPS_TOKEN; do
    grep -qx "$name" <<<"$existing_secrets" || missing+=("$name")
  done
  if (( ${#missing[@]} == 0 )); then
    say "✓ the bootstrap's secrets are on $PROJECT_REPO"
    break
  fi
  warn "$PROJECT_REPO is still missing: ${missing[*]}"
  warn "The bootstrap hasn't run, or failed. Run step 3 above (see its output)."
done

# ── Stage 3: Access credentials + callback URL ────────────────────────────
stage "Set the project's Access secrets and callback URL"
say "The project's CI sends the Access service token on every callback to the"
say "control plane, at PROJECT_OPS_URL (the platform's dashboard URL)."
CF_ACCESS_CLIENT_ID=$(_existing CF_ACCESS_CLIENT_ID || true)
CF_ACCESS_CLIENT_SECRET=$(_existing CF_ACCESS_CLIENT_SECRET || true)
PROJECT_OPS_URL=$(_existing DASHBOARD_URL || true)
if [[ -z "$CF_ACCESS_CLIENT_ID" || -z "$CF_ACCESS_CLIENT_SECRET" || -z "$PROJECT_OPS_URL" ]]; then
  warn "Missing CF_ACCESS_CLIENT_ID, CF_ACCESS_CLIENT_SECRET or DASHBOARD_URL in $ENV_FILE."
  warn "Run scripts/deploy-wizard.sh first."
  exit 1
fi
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  # Values go in on stdin, never as arguments, so they don't show up in `ps`.
  for name in CF_ACCESS_CLIENT_ID CF_ACCESS_CLIENT_SECRET; do
    if printf '%s' "${!name}" | gh secret set "$name" --repo "$PROJECT_REPO" >/dev/null; then
      WRITTEN_SECRET+=("$name") && say "✓ $name"
    else
      SKIPPED+=("$PROJECT_REPO secret $name (gh secret set $name --repo $PROJECT_REPO)")
    fi
  done
  if gh variable set PROJECT_OPS_URL --repo "$PROJECT_REPO" --body "$PROJECT_OPS_URL" >/dev/null; then
    say "✓ PROJECT_OPS_URL (variable)"
  else
    SKIPPED+=("$PROJECT_REPO variable PROJECT_OPS_URL")
  fi
else
  warn "gh not authenticated. Run these yourself (each prompts for the value):"
  note "  gh secret set CF_ACCESS_CLIENT_ID --repo $PROJECT_REPO"
  note "  gh secret set CF_ACCESS_CLIENT_SECRET --repo $PROJECT_REPO"
  note "  gh variable set PROJECT_OPS_URL --repo $PROJECT_REPO --body $PROJECT_OPS_URL"
  SKIPPED+=("$PROJECT_REPO repo secrets/variable (see commands above)")
fi
say ""
say "Check it end to end once the project's own app secrets are set (its README"
say "lists them): open a PR into its 'staging' branch and follow it through."
step "The project's PR workflow provisions pr-{n} and records the Deployment."
open_url "https://github.com/${PROJECT_REPO}/actions"
step "Open the dashboard and confirm the PR environment shows, with status and commit."
open_url "$PROJECT_OPS_URL"

finish
