#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# Persist captured values at the repo root .env (gitignored). Alchemy reads it.
ENV_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/.env"

banner "Phase 6 — deploy the platform behind Cloudflare Access"

# ── Stage 1: Alchemy identity ─────────────────────────────────────────────
stage "Connect Alchemy to Cloudflare"
say "One-time OAuth sign-in, cached to ~/.alchemy — the same idea as"
say "'wrangler login'. This is also what 'pnpm dev' (alchemy dev) needs; it"
say "authenticates you but changes nothing on the account."
pause "Run 'pnpm alchemy login' in another terminal, finish the browser flow, then Enter."

# ── Stage 2: Cloudflare account + API token ───────────────────────────────
stage "Cloudflare: account ID + API token"
say "The deploy also needs a scoped API token (login alone isn't enough for the"
say "Access + Secrets Store providers). This token is also what the control-plane"
say "uses to query Workers Observability (ADR-0004), so it lands in Secrets Store."
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages"
step "Copy the Account ID from the right-hand sidebar (32 hex characters)."
ask CLOUDFLARE_ACCOUNT_ID "Paste the account ID:"
open_url "https://dash.cloudflare.com/profile/api-tokens"
step "Create Token → Create Custom Token. Add these ACCOUNT permissions (Edit):"
note "  Workers Scripts · D1 · Workers Observability · Workers R2 Storage ·"
note "  Cloudflare Secrets Store · Access: Apps and Policies ·"
note "  Access: Service Tokens · Access: Organizations, IdPs, and Groups"
warn "Permission names drift — cross-check against Alchemy's Cloudflare docs if a"
warn "deploy step 403s, then re-run this wizard (Enter keeps saved values)."
step "Create the token and copy it (shown once)."
ask_secret CLOUDFLARE_API_TOKEN "Paste the API token:"
write_env CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"
write_env CLOUDFLARE_API_TOKEN "$CLOUDFLARE_API_TOKEN"

# ── Stage 3: Zero Trust org + Google IdP ──────────────────────────────────
stage "Cloudflare Zero Trust: team + Google login"
say "The dashboard sits behind an interactive Google login; the API behind a"
say "service token. Both live in your Zero Trust organization."
open_url "https://one.dash.cloudflare.com/"
step "If prompted, create a Zero Trust organization. Pick a team name — this is"
step "your team domain: <team>.cloudflareaccess.com."
ask CF_ACCESS_TEAM_DOMAIN "Team name only (the <team> part, no .cloudflareaccess.com):"
say ""
step "Settings → Authentication → Login methods → Add new → Google."
note "Google needs an OAuth client (console.cloud.google.com → Credentials →"
note "OAuth client ID → Web application). Redirect URI is shown on the Cloudflare"
note "form. Save the client ID + secret into the Cloudflare Google IdP form."
step "After saving, the Google IdP shows in the login-methods list. Get its UUID:"
open_url "https://developers.cloudflare.com/api/resources/zero_trust/subresources/identity_providers/methods/list/"
note "Easiest: run"
note "  curl -s -H \"Authorization: Bearer \$CLOUDFLARE_API_TOKEN\" \\"
note "    https://api.cloudflare.com/client/v4/accounts/\$CLOUDFLARE_ACCOUNT_ID/access/identity_providers \\"
note "    | jq -r '.result[] | select(.type==\"google\") | .id'"
ask CF_GOOGLE_IDP_ID "Paste the Google IdP UUID:"
write_env CF_ACCESS_TEAM_DOMAIN "$CF_ACCESS_TEAM_DOMAIN"
write_env CF_GOOGLE_IDP_ID "$CF_GOOGLE_IDP_ID"

# ── Stage 4: deploy the platform ──────────────────────────────────────────
stage "Deploy: alchemy deploy"
say "Stands up: control-plane Worker, dashboard, D1 (+ migrations), the Access"
say "application + service token, and the Secrets Store entry."
note "Alchemy reads the .env this wizard just wrote, plus your ~/.alchemy login."
warn "The first deploy bootstraps the remote state store — approve the one prompt."
warn "Not yet proven end to end (ADR-0009) — watch for adapter / binding errors."
pause "Run 'pnpm alchemy deploy' now in another terminal. Enter when it finishes."
say ""
say "From the deploy output ('return { ... }' / the resource table):"
ask IDP_API_URL "control-plane URL (controlPlaneUrl):"
ask DASHBOARD_URL "dashboard URL (dashboardUrl):"
step "The Access service token client id + secret are printed once by Cloudflare"
step "(serviceTokenClientId in the output; the secret in the deploy log or the"
step "Zero Trust dashboard → Access → Service Tokens)."
ask CF_ACCESS_CLIENT_ID "Service token Client ID:"
ask_secret CF_ACCESS_CLIENT_SECRET "Service token Client Secret:"
write_env IDP_API_URL "$IDP_API_URL"
write_env DASHBOARD_URL "$DASHBOARD_URL"
write_env CF_ACCESS_CLIENT_ID "$CF_ACCESS_CLIENT_ID"
write_env CF_ACCESS_CLIENT_SECRET "$CF_ACCESS_CLIENT_SECRET"

# ── Stage 5: register demo-project, mint its token ────────────────────────
stage "Register the managed project"
say "demo-project needs its own per-project bearer token (P1-02/03). We register"
say "it against the deployed control-plane, through the Access perimeter."
ask DEMO_REPO "demo-project's GitHub slug (owner/repo):"
say ""
say "Running the registration call now:"
REGISTER_RESP=$(curl -fsS -X POST "$IDP_API_URL/v1/projects" \
  -H "CF-Access-Client-Id: $CF_ACCESS_CLIENT_ID" \
  -H "CF-Access-Client-Secret: $CF_ACCESS_CLIENT_SECRET" \
  -H "Content-Type: application/json" \
  -d "$(printf '{"name":"demo-project","githubRepo":"%s"}' "$DEMO_REPO")" || true)
if [[ -z "$REGISTER_RESP" ]]; then
  warn "Registration call failed. Register by hand (same curl) and paste the token."
  ask_secret IDP_PROJECT_TOKEN "demo-project control-plane token:"
else
  IDP_PROJECT_TOKEN=$(printf '%s' "$REGISTER_RESP" | jq -r '.token')
  say "Registered. Token captured."
fi
write_env IDP_PROJECT_TOKEN "$IDP_PROJECT_TOKEN"

# ── Stage 6: demo-project repo secrets ────────────────────────────────────
stage "Set demo-project's GitHub secrets"
say "preview.yml (P6-05) sends the Access service token + bearer token on every"
say "callback. Setting them on $DEMO_REPO now."
if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
  gh secret   set CF_ACCESS_CLIENT_ID     --repo "$DEMO_REPO" --body "$CF_ACCESS_CLIENT_ID"     && say "✓ CF_ACCESS_CLIENT_ID"
  gh secret   set CF_ACCESS_CLIENT_SECRET --repo "$DEMO_REPO" --body "$CF_ACCESS_CLIENT_SECRET" && say "✓ CF_ACCESS_CLIENT_SECRET"
  gh secret   set IDP_PROJECT_TOKEN       --repo "$DEMO_REPO" --body "$IDP_PROJECT_TOKEN"       && say "✓ IDP_PROJECT_TOKEN"
  gh secret   set CLOUDFLARE_API_TOKEN    --repo "$DEMO_REPO" --body "$CLOUDFLARE_API_TOKEN"    && say "✓ CLOUDFLARE_API_TOKEN"
  gh secret   set CLOUDFLARE_ACCOUNT_ID   --repo "$DEMO_REPO" --body "$CLOUDFLARE_ACCOUNT_ID"   && say "✓ CLOUDFLARE_ACCOUNT_ID (secret)"
  gh variable set IDP_API_URL             --repo "$DEMO_REPO" --body "$IDP_API_URL"             && say "✓ IDP_API_URL (variable)"
else
  warn "gh not authenticated. Run these yourself:"
  note "  gh secret set CF_ACCESS_CLIENT_ID --repo $DEMO_REPO"
  note "  gh secret set CF_ACCESS_CLIENT_SECRET --repo $DEMO_REPO"
  note "  gh secret set IDP_PROJECT_TOKEN --repo $DEMO_REPO"
  note "  gh secret set CLOUDFLARE_API_TOKEN --repo $DEMO_REPO"
  note "  gh secret set CLOUDFLARE_ACCOUNT_ID --repo $DEMO_REPO"
  note "  gh variable set IDP_API_URL --repo $DEMO_REPO --body $IDP_API_URL"
  SKIPPED+=("demo-project repo secrets/variable — see commands above")
fi

# ── Stage 7: end-to-end verification (P6-06) ──────────────────────────────
stage "Verify the whole chain (P6-06)"
say "Open a real PR on demo-project and follow it through:"
step "Push a branch and open a PR against 'staging'."
step "preview.yml → alchemy provisions pr-{n} → callback records the Deployment."
open_url "https://github.com/${DEMO_REPO}/actions"
step "The Actions run should post a preview-URL comment on the PR."
say ""
step "Open the dashboard (Google login — you'll be prompted):"
open_url "$DASHBOARD_URL"
step "Confirm the PR environment shows, with status and commit SHA."
say ""
step "Merge into 'staging' → integration tests run once, live."
step "Merge 'staging' → 'main' → prod deploys; the production view updates."
if confirm "Did the whole chain complete and show in the dashboard?"; then
  say "Phase 6 done. Check off P6-06 in docs/ROADMAP.md."
else
  warn "Note where it broke; the Actions logs + dashboard 'recent errors' help."
fi

finish
